# Generated by Django 5.0 on 2026-05-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_coupon_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
