# Generated by Django 5.0 on 2026-05-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_coupon_discount_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='flavor',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
