# Generated by Django 5.0 on 2026-05-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_menu_flavor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='flavor',
        ),
        migrations.AddField(
            model_name='menu',
            name='flavors',
            field=models.ManyToManyField(to='menu.flavor'),
        ),
    ]
